import type { Metadata } from "next";
import { Permanent_Marker, Geist, Patrick_Hand } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import { ReactLenis } from "lenis/react";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import LeafCursor from "@/components/global/LeafCursor";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const permanentMarker = Permanent_Marker({
  variable: "--font-permanent-marker",
  subsets: ["latin"],
  weight: "400",
});

const patrick = Patrick_Hand({
  variable: "--font-patrick-hand",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        permanentMarker.variable,
        patrick.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body>
        <ReactLenis root />
        <LeafCursor zIndex={10000} />
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
